apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: sbbk9bgua-nodejs 
  janus-idp.io/tekton: sbbk9bgua-nodejs
  backstage.io/kubernetes-id: sbbk9bgua-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sbbk9bgua-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml