apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sbbk9bgua-nodejs-gitops
  description: This is GitOps manifest for sbbk9bgua-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=sbbk9bgua-nodejs
    backstage.io/kubernetes-id: sbbk9bgua-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: sbbk9bgua-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sbbk9bgua-nodejs
